name: Audit

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - develop
    paths:
      - "**/Cargo.lock"
      - "**/Cargo.toml"
      - ".github/workflows/audit.yml"
  pull_request:
    branches:
      - develop
    paths:
      - "**/Cargo.lock"
      - "**/Cargo.toml"
      - ".github/workflows/audit.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}